osx_image: xcode7.3

matrix:
  include:
    - os: osx
      env: TEST_FILES=BuildTest,linuxPackagerTest,globTest NODE_VERSION=7 PUBLISH_TO_NPM=true

    - os: osx
      env: TEST_FILES=winPackagerTest,nsisTest,macPackagerTest NODE_VERSION=6

    - os: osx
      env: TEST_FILES=macPackagerTest,CodeSignTest NODE_VERSION=6

language: c

cache:
  directories:
    - node_modules
    - $HOME/.electron

before_install:
  - curl -L https://dl.bintray.com/develar/bin/7za -o /tmp/7za
  - chmod +x /tmp/7za
  - curl -L https://dl.bintray.com/develar/bin/wine.7z -o /tmp/wine.7z
  - /tmp/7za x -o/usr/local/Cellar -y /tmp/wine.7z
  - brew link --overwrite fontconfig gd gnutls jasper libgphoto2 libicns libtasn1 libusb libusb-compat little-cms2 nettle openssl sane-backends webp wine git-lfs gnu-tar dpkg xz
  - brew install freetype graphicsmagick
  - git-lfs pull

install:
- nvm install $NODE_VERSION
- nvm use --delete-prefix $NODE_VERSION
- mkdir -p ~/Library/Caches/Yarn
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$PATH:$HOME/.yarn/bin"
- yarn install --pure-lockfile
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" && "$AUTO_PUBLISH" != "false" && "$TRAVIS_TAG" == "" && "$PUBLISH_TO_NPM" == "true" ]]; then yarn add @develar/semantic-release@next --dev ; fi

script:
- yarn run test

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" && "$AUTO_PUBLISH" != "false" && "$TRAVIS_TAG" == "" && "$PUBLISH_TO_NPM" == "true" ]]; then npm run semantic-release ; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"