os:
  - linux
  - osx

osx_image: xcode7

dist: trusty
sudo: required

services:
  - docker

env:
  - NODE_VERSION=4
  - NODE_VERSION=6

language: c

cache:
  directories:
    - node_modules
    - test/testApp/node_modules
    - $HOME/.electron
    - $HOME/.cache/fpm

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar dpkg libicns graphicsmagick git-lfs lzip; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-linux-amd64-1.2.0.tar.gz | tar -xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git-lfs-1.2.0/git-lfs pull; fi

install:
- nvm install $NODE_VERSION
- npm install npm -g
- npm install
- npm prune

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run test ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v ${PWD}:/project -v ~/.electron:/root/.electron electronuserland/electron-builder:wine /test.sh ; fi

after_success:
- node out/cleanup.js
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" && "$AUTO_PUBLISH" != "false" ]]; then npm run semantic-release ; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"