osx_image: xcode11.3
language: node_js

env:
  global:
    - FORCE_COLOR=1

matrix:
  include:
    - os: osx
      env: TEST_FILES=BuildTest,extraMetadataTest,globTest,filesTest,ignoreTest,linux,windows,macPackagerTest,protonTest
      node_js: "12"

    - os: osx
      env: TEST_FILES=CodeSignTest,macArchiveTest,macIconTest
      node_js: "12"

    - os: osx
      env: TEST_FILES=masTest,dmgTest
      node_js: "12"

cache:
  yarn: true
  directories:
    - .yarn
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder
    - /tmp/jest-electron-builder-tests

install:
  - YARN_CHECKSUM_BEHAVIOR=ignore node .yarn/releases/yarn-2.1.1.js install

script:
  - node .yarn/releases/yarn-2.1.1.js pretest
  - node .yarn/releases/yarn-2.1.1.js node ./test/out/helpers/runTests.js

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"