osx_image: xcode8.3
language: node_js

matrix:
  include:
    - os: osx
      env: TEST_FILES=BuildTest,extraMetadataTest,globTest,filesTest,ignoreTest,linux.*,windows.*
      node_js: "8"

    - os: osx
      env: TEST_FILES=CodeSignTest,macArchiveTest,macPackagerTest
      node_js: "8"

    - os: osx
      env: TEST_FILES=masTest,dmgTest
      node_js: "6"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder
    - /tmp/jest-electron-builder-tests

install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv dist $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn

script:
  - yarn test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"