osx_image: xcode10.2
language: node_js

env:
  global:
    - FORCE_COLOR=1

matrix:
  include:
    - os: osx
      env: TEST_FILES=BuildTest,extraMetadataTest,globTest,filesTest,ignoreTest,linux,windows,macIconTest
      node_js: "10"

    - os: osx
      env: TEST_FILES=CodeSignTest,macArchiveTest,macPackagerTest
      node_js: "10"

    - os: osx
      env: TEST_FILES=masTest,dmgTest,protonTest
      node_js: "10"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder
    - /tmp/jest-electron-builder-tests

install:
  - yarn --frozen-lockfile

script:
  - yarn test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"