platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

environment:
  TEST_FILES: BuildTest,extraMetadataTest,filesTest,globTest,nsisUpdaterTest,nsisTest

install:
  - ps: Install-Product node 6 x64
  - node ./test/vendor/yarn.js

build: off

test_script:
  - node ./test/vendor/yarn.js test