site_name: electron-builder
site_url: https://www.electron.build
use_directory_urls: false
theme:
  feature:
    tabs: true
  name: material
#  logo:
#    icon: 'build'
  palette:
    primary: 'blue'
    accent: 'blue'

repo_name: electron-userland/electron-builder
repo_url: 'https://github.com/electron-userland/electron-builder'
edit_uri: ""
strict: true

extra:
  analytics:
    provider: google
    property: UA-105592680-1

extra_javascript:
  - extra.js

markdown_extensions:
  - admonition
  - smarty
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - Command Line Interface (CLI): cli.md
  - Programmatic API:
      API: api/electron-builder.md
      Example: api/programmaticUsage.md
  - Donate: donate.md

  - Configuration:
      - Common Configuration: configuration/configuration.md

      - Application Contents: configuration/contents.md
      - File Patterns: file-patterns.md

      - macOS:
          - Any macOS Target: configuration/mac.md
          - DMG: configuration/dmg.md
          - MAS: configuration/mas.md
          - PKG: configuration/pkg.md

      - Windows:
          - Any Windows Target: configuration/win.md
          - NSIS: configuration/nsis.md
          - AppX: configuration/appx.md
          - Squirrel.Windows: configuration/squirrel-windows.md

      - Linux:
          - Any Linux Target: configuration/linux.md
          - AppImage: configuration/appimage.md
          - Snap: configuration/snap.md

      - Publish: configuration/publish.md

  - Guides:
      - Icons: icons.md
      - Auto Update: auto-update.md
      - Code Signing: code-signing.md
      - Multi Platform Build: multi-platform-build.md

  - Tutorials:
      - Loading App Dependencies Manually: tutorials/loading-app-dependencies-manually.md
      - Two package.json Structure: tutorials/two-package-structure.md
      - macOS Kernel Extensions: tutorials/macos-kernel-extensions.md
      - Sign a Windows app on macOS/Linux: tutorials/code-signing-windows-apps-on-unix.md
      - Release Using Channels: tutorials/release-using-channels.md
      - Test Update on s3 Locally: tutorials/test-update-on-s3-locally.md