version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12.18.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - install-dep-cache-{{ checksum "yarn.lock" }}-{{ checksum ".yarn/releases/yarn-2.1.1.js" }}
      - restore_cache:
          keys:
            - v-8.2.5-electron
      - run:
          command: YARN_CHECKSUM_BEHAVIOR=ignore node .yarn/releases/yarn-2.1.1.js install
      - run:
          command: node .yarn/releases/yarn-2.1.1.js pretest
      - run:
          command: cp .pnp.js .yarn/.pnp.js
      - save_cache:
          key: install-dep-cache-{{ checksum "yarn.lock" }}-{{ checksum ".yarn/releases/yarn-2.1.1.js" }}
          paths:
            - .yarn
      - run:
          command: node .yarn/releases/yarn-2.1.1.js node ./test/out/helpers/downloadElectron.js
      - save_cache:
          key: v-8.2.5-electron
          paths:
            - ~/.cache/electron

  test:
    parallelism: 4
    docker:
      - image: electronuserland/builder:wine-mono
        environment:
          JEST_JUNIT_OUTPUT_DIR: /tmp/test-reports/test.xml
          TZ: Europe/Berlin
    steps:
      - checkout
      - restore_cache:
          keys:
            - install-dep-cache-{{ checksum "yarn.lock" }}-{{ checksum ".yarn/releases/yarn-2.1.1.js" }}
      - restore_cache:
          keys:
            - v-8.2.5-electron
      # because in the build job we use circleci docker image and circleci restores cache to original user home
      - run:
          command: |
            rm -rf .yarn
            mv /home/circleci/project/.yarn .yarn
            mv .yarn/.pnp.js .pnp.js
            mkdir -p ~/.cache
            mv /home/circleci/.cache/electron ~/.cache/electron
      - run:
          # do not use yarn test because lint is done in the build job
          command: |
            node .yarn/releases/yarn-2.1.1.js compile
            node .yarn/releases/yarn-2.1.1.js node ./test/out/helpers/runTests.js
      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - docs
      - test:
          filters:
            branches:
              ignore:
                - docs
          requires:
            - build