version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - install-dep-cache-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            - v-11.0.0-electron
      - run:
          command: node .yarn/releases/yarn-2.2.2.cjs install
      - run:
          command: node .yarn/releases/yarn-2.2.2.cjs pretest
      - run:
          command: cp .pnp.js .yarn/.pnp.js
      - save_cache:
          key: install-dep-cache-{{ checksum "yarn.lock" }}
          paths:
            - .yarn
      - run:
          command: node .yarn/releases/yarn-2.2.2.cjs node ./test/out/helpers/downloadElectron.js
      - save_cache:
          key: v-11.0.0-electron
          paths:
            - ~/.cache/electron

  test:
    parallelism: 4
    docker:
      - image: electronuserland/builder:wine-mono
        environment:
          JEST_JUNIT_OUTPUT_DIR: /tmp/test-reports/test.xml
          TZ: Europe/Berlin
    steps:
      - checkout
      - restore_cache:
          keys:
            - install-dep-cache-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            - v-11.0.0-electron
      # because in the build job we use circleci docker image and circleci restores cache to original user home
      - run:
          command: |
            mkdir -p ~/.cache
            mv /home/circleci/.cache/electron ~/.cache/electron
            node .yarn/releases/yarn-2.2.2.cjs install
      - run:
          # do not use yarn test because lint is done in the build job
          command: |
            node .yarn/releases/yarn-2.2.2.cjs compile
            node .yarn/releases/yarn-2.2.2.cjs node ./test/out/helpers/runTests.js
      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - docs
      - test:
          filters:
            branches:
              ignore:
                - docs
          requires:
            - build