version: 2

jobs:
  build:
    docker:
      - image: circleci/node:14.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - install-dep-cache-{{ checksum "pnpm-lock.yaml" }}
      - restore_cache:
          keys:
            - v-11.0.0-electron
      - run:
          command: npm i --prefix=$HOME/.local -g pnpm
      - run:
          command: pnpm install --frozen-lockfile
      - run:
          command: pnpm compile
      - save_cache:
          key: install-dep-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          command: node ./test/out/helpers/downloadElectron.js
      - save_cache:
          key: v-11.0.0-electron
          paths:
            - ~/.cache/electron

  test:
    parallelism: 4
    docker:
      - image: electronuserland/builder:wine-mono-05.21@sha256:72d80fa707b724f7e08d42f97d960506445d6d6ffe8d0fa94c805c309644ee2a
        environment:
          JEST_JUNIT_OUTPUT_DIR: /tmp/test-reports/test.xml
          TZ: Europe/Berlin
    steps:
      - checkout
      - restore_cache:
          keys:
            - install-dep-cache-{{ checksum "pnpm-lock.yaml" }}
      - restore_cache:
          keys:
            - v-11.0.0-electron
      # because in the build job we use circleci docker image and circleci restores cache to original user home
      - run:
          command: |
            curl -L https://unpkg.com/@pnpm/self-installer | node
            mkdir -p ~/.cache
            mv /home/circleci/.cache/electron ~/.cache/electron
            pnpm install --frozen-lockfile
      - run:
          # do not use yarn test because lint is done in the build job
          command: pnpm run compile
      - run:
          command: node ./test/out/helpers/runTests.js
      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - docs
      - test:
          filters:
            branches:
              ignore:
                - docs
          requires:
            - build