name: 'Netlify Deploy - Release'

on:
  release:
    types: ['published']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  statuses: write

jobs:
  deploy:
    name: 'Deploy Release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install deps and audit
        uses: ./.github/actions/pnpm

      - name: Build typdoc site
        run: pnpm docs:all

      - uses: jsmrcaga/action-netlify-deploy@06b6a09e152823cce0d76c0dbb22b914934de198 # v2.3.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
          debug: true
          build_directory: "site"
          monorepo_package: "electron-builder"

      # Creates a status check with link to preview
      - name: Set Status check on commit
        uses: guibranco/github-status-action-v2@0849440ec82c5fa69b2377725b9b7852a3977e76 # v1.1.13
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success
          context: Netlify Documentation Site preview
          description: Production - Click "details"
          target_url: ${{ env.NETLIFY_PREVIEW_URL }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}