name: Release

on:
  push:
    branches:
      - master

env:
  HUSKY: 0 # Bypass husky commit hook for CI

permissions: {}

jobs:
  pr-release:
    permissions:
      id-token: write  # Required for OIDC token
    environment: release
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          persist-credentials: false

      - name: Install dependencies
        uses: ./.github/actions/pnpm

      - name: Generate GitHub App token
        uses: electron/github-app-auth-action@e25ab7f5aa15b949aee0f00d7e48972f1f3e0f5a
        id: generate-token
        with:
          export-git-user: true
          creds: ${{ secrets.RELEASE_BOT_APP_CREDS }}

      - name: Create versions PR & prepare publish
        uses: changesets/action@7af85527bb2f43a404b5823a6cad47661be255c1 # v1.5.3 - @marshallofsound fork
        with:
          version: pnpm ci:version
          commit: 'chore(deploy): Release'
          title: 'chore(deploy): Release'
          publish: pnpm ci:publish
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
