name: Release

on:
  push:
    branches:
      - master

env:
  HUSKY: 0 # Bypass husky commit hook for CI

permissions: {}
jobs:
  pr-release:
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)

    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Install deps and audit
        uses: ./.github/actions/pnpm

      - name: Set up NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create versions PR & prepare publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: 'chore(deploy): Release'
          title: 'chore(deploy): Release'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
